# Generated by Django 3.0 on 2019-12-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.FloatField(help_text='Longitude')),
                ('Latitude', models.FloatField(help_text='Latitude')),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=100)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('', '')], default='', help_text='When the sighting session occured', max_length=2)),
                ('Date', models.CharField(help_text='The date of sighting session', max_length=10)),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'JUVENILE'), ('', '')], default='', help_text='Whether a squirrel is an adult', max_length=10)),
                ('Primary_Fur_Color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('', '')], default='', help_text='Primary fur color', max_length=10)),
                ('Location', models.CharField(choices=[('ground plane', 'ground plane'), ('above ground', 'above ground'), ('', '')], default='', help_text='squirrel location', max_length=50)),
                ('Specific_Location', models.CharField(help_text='Specific Location of squirrels', max_length=100)),
                ('Running', models.BooleanField(default=False)),
                ('Chasing', models.BooleanField(default=False)),
                ('Climbing', models.BooleanField(default=False)),
                ('Eating', models.BooleanField(default=False)),
                ('Foraging', models.BooleanField(default=False)),
                ('Other_Activities', models.CharField(help_text='Other activities squirrels are doing', max_length=100)),
                ('Kuks', models.BooleanField(default=False)),
                ('Quaas', models.BooleanField(default=False)),
                ('Moans', models.BooleanField(default=False)),
                ('Tail_flags', models.BooleanField(default=False)),
                ('Tail_twitches', models.BooleanField(default=False)),
                ('Approaches', models.BooleanField(default=False)),
                ('Indifferent', models.BooleanField(default=False)),
                ('Runs_from', models.BooleanField(default=False)),
            ],
        ),
    ]
